version: "3.3" # or a different version that suits your Docker environment

services:
  panel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SCORE_FILE=/data/score_snw_station_diff_alti.nc
      - SERIES_FILE=/data/series_snw_station_diff_alti.nc
    volumes:
      - ./data:/data
      - ./SnowExplorer-V5.ipynb:/snowexplorer.ipynb  