name: Pull Request - Build and Push Docker Images to GHCR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: read
      checks: read
      deployments: read
      issues: read
      statuses: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to get commit information

      - name: Get list of changed files
        id: get_changed_files
        run: |
          # Get the list of changed files and convert to JSON format
          changed_files=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}")
          changed_files_json=$(echo "$changed_files" | jq -R -s -c 'split("\n")[:-1]')
          echo "changed_files_json=$changed_files_json" >> $GITHUB_OUTPUT

      - name: Generate list of Dockerfiles to build
        id: generate_dockerfile_list
        run: |
          # Convert JSON array of changed files back to bash array
          changed_files=$(echo '${{ steps.get_changed_files.outputs.changed_files_json }}' | jq -r '.[]')

          dockerfiles_to_build=()
          while IFS= read -r file; do
            # Check if the changed file is a Dockerfile
            if [[ $file == *Dockerfile ]]; then
              dockerfiles_to_build+=($file)
            # Check if the directory of the changed file contains a Dockerfile
            elif [[ -f $(dirname "$file")/Dockerfile ]]; then
              dockerfiles_to_build+=($(dirname "$file")/Dockerfile)
            fi

            # Check if the file is in manage-containers and add the top-level Dockerfile if it exists
            if [[ $file == manage-containers/*/* ]]; then
              top_level_dir=$(echo "$file" | cut -d'/' -f1-2)
              if [[ -f "$top_level_dir/Dockerfile" ]]; then
                dockerfiles_to_build+=($top_level_dir/Dockerfile)
              fi
            fi
          done <<< "$changed_files"

          # Remove duplicates from dockerfiles_to_build
          unique_dockerfiles_to_build=($(echo "${dockerfiles_to_build[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
          
          echo "Dockerfiles to build: ${unique_dockerfiles_to_build[@]}"
          echo "dockerfile_dirs=${unique_dockerfiles_to_build[@]}" >> $GITHUB_OUTPUT
